# Linter Options
rules:
  no-css-comments: 0
  quotes: 0
  indentation: 0
  class-name-format: 0
  no-trailing-whitespace: 0
  empty-line-between-blocks: 0
  property-sort-order: 0
  declarations-before-nesting: 0
  # no-vendor-prefixes: 0
  no-important: 0
  no-color-literals: 0
  mixins-before-declarations: 0
  no-empty-rulesets: 0
  placeholder-in-extend: 0
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  no-qualifying-elements: 0
  final-newline: 0
  no-color-keywords: 0
  force-element-nesting: 0
  no-misspelled-properties: 0
  space-around-operator: 0
  